#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral DLMB_CNTLR */
#define XPAR_DLMB_CNTLR_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_DLMB_CNTLR_BASEADDR 0x0
#define XPAR_DLMB_CNTLR_HIGHADDR 0xffff
#define XPAR_DLMB_CNTLR_DATA_WIDTH 0x20
#define XPAR_DLMB_CNTLR_ECC 0x0
#define XPAR_DLMB_CNTLR_FAULT_INJECT 0x0
#define XPAR_DLMB_CNTLR_CE_FAILING_REGISTERS 0x0
#define XPAR_DLMB_CNTLR_UE_FAILING_REGISTERS 0x0
#define XPAR_DLMB_CNTLR_ECC_ONOFF_REGISTER 0x0
#define XPAR_DLMB_CNTLR_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_DLMB_CNTLR_WRITE_ACCESS 0x2

/* Canonical definitions for peripheral DLMB_CNTLR */
#define XPAR_XBRAM_0_BASEADDR 0x0
#define XPAR_XBRAM_0_HIGHADDR 0xffff
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x2

#define XPAR_XIOMODULE_NUM_INSTANCES 1

/* Definitions for peripheral IOMODULE_0 */
#define XPAR_IOMODULE_0_COMPATIBLE "xlnx,iomodule-3.1"
#define XPAR_IOMODULE_0_BASEADDR 0x80000000
#define XPAR_IOMODULE_0_HIGHADDR 0x8000ffff
#define XPAR_IOMODULE_0_BASEADDR_1 0xc0000000
#define XPAR_IOMODULE_0_INTC_HAS_FAST 0x1
#define XPAR_IOMODULE_0_INTC_BASE_VECTORS 0x0
#define XPAR_IOMODULE_0_INTC_ADDR_WIDTH 0x10
#define XPAR_IOMODULE_0_INTC_LEVEL_EDGE 0x7fff
#define XPAR_IOMODULE_0_OPTIONS 0x1
#define XPAR_IOMODULE_0_CLOCK_FREQ 0x2faf080
#define XPAR_IOMODULE_0_UART_BAUDRATE 0x1c200
#define XPAR_IOMODULE_0_PIT_USED_0 0
#define XPAR_IOMODULE_0_PIT_USED_1 0
#define XPAR_IOMODULE_0_PIT_USED_2 0
#define XPAR_IOMODULE_0_PIT_USED_3 0
#define XPAR_IOMODULE_0_PIT_SIZE_0 32
#define XPAR_IOMODULE_0_PIT_SIZE_1 32
#define XPAR_IOMODULE_0_PIT_SIZE_2 32
#define XPAR_IOMODULE_0_PIT_SIZE_3 32
#define XPAR_IOMODULE_0_PIT_MASK_0 4294967295
#define XPAR_IOMODULE_0_PIT_MASK_1 4294967295
#define XPAR_IOMODULE_0_PIT_MASK_2 4294967295
#define XPAR_IOMODULE_0_PIT_MASK_3 4294967295
#define XPAR_IOMODULE_0_PIT_PRESCALER_0 0
#define XPAR_IOMODULE_0_PIT_PRESCALER_1 0
#define XPAR_IOMODULE_0_PIT_PRESCALER_2 0
#define XPAR_IOMODULE_0_PIT_PRESCALER_3 0
#define XPAR_IOMODULE_0_PIT_READABLE_0 1
#define XPAR_IOMODULE_0_PIT_READABLE_1 1
#define XPAR_IOMODULE_0_PIT_READABLE_2 1
#define XPAR_IOMODULE_0_PIT_READABLE_3 1
#define XPAR_IOMODULE_0_GPO_INIT_0 0
#define XPAR_IOMODULE_0_GPO_INIT_1 0
#define XPAR_IOMODULE_0_GPO_INIT_2 0
#define XPAR_IOMODULE_0_GPO_INIT_3 0
#define XPAR_IOMODULE_0_MAX_INTR_SIZE 0x0
#define XPAR_IOMODULE_0_INTC_INTR_SIZE 0x1
#define XPAR_IOMODULE_0_INTC_USE_EXT_INTR 0x0
#define XPAR_IOMODULE_0_INTC_POSITIVE 0xffff
#define XPAR_IOMODULE_0_UART_PROG_BAUDRATE 0x0
#define XPAR_IOMODULE_0_UART_DATA_BITS 0x8
#define XPAR_IOMODULE_0_UART_USE_PARITY 0x0
#define XPAR_IOMODULE_0_UART_ODD_PARITY 0x0
#define XPAR_IOMODULE_0_UART_RX_INTERRUPT 0x0
#define XPAR_IOMODULE_0_UART_TX_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_UART_RX 0x1
#define XPAR_IOMODULE_0_USE_UART_TX 0x1
#define XPAR_IOMODULE_0_UART_ERROR_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_FIT1 0x0
#define XPAR_IOMODULE_0_FIT1_NO_CLOCKS 0x1848
#define XPAR_IOMODULE_0_FIT1_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_FIT2 0x0
#define XPAR_IOMODULE_0_FIT2_NO_CLOCKS 0x1848
#define XPAR_IOMODULE_0_FIT2_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_FIT3 0x0
#define XPAR_IOMODULE_0_FIT3_NO_CLOCKS 0x1848
#define XPAR_IOMODULE_0_FIT3_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_FIT4 0x0
#define XPAR_IOMODULE_0_FIT4_NO_CLOCKS 0x1848
#define XPAR_IOMODULE_0_FIT4_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_PIT1 0x0
#define XPAR_IOMODULE_0_PIT1_SIZE 0x20
#define XPAR_IOMODULE_0_PIT1_READABLE 0x1
#define XPAR_IOMODULE_0_PIT1_PRESCALER 0x0
#define XPAR_IOMODULE_0_PIT1_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_PIT2 0x0
#define XPAR_IOMODULE_0_PIT2_SIZE 0x20
#define XPAR_IOMODULE_0_PIT2_READABLE 0x1
#define XPAR_IOMODULE_0_PIT2_PRESCALER 0x0
#define XPAR_IOMODULE_0_PIT2_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_PIT3 0x0
#define XPAR_IOMODULE_0_PIT3_SIZE 0x20
#define XPAR_IOMODULE_0_PIT3_READABLE 0x1
#define XPAR_IOMODULE_0_PIT3_PRESCALER 0x0
#define XPAR_IOMODULE_0_PIT3_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_PIT4 0x0
#define XPAR_IOMODULE_0_PIT4_SIZE 0x20
#define XPAR_IOMODULE_0_PIT4_READABLE 0x1
#define XPAR_IOMODULE_0_PIT4_PRESCALER 0x0
#define XPAR_IOMODULE_0_PIT4_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_GPO1 0x1
#define XPAR_IOMODULE_0_GPO1_SIZE 0x8
#define XPAR_IOMODULE_0_GPO1_INIT 0x0
#define XPAR_IOMODULE_0_USE_GPO2 0x1
#define XPAR_IOMODULE_0_GPO2_SIZE 0x10
#define XPAR_IOMODULE_0_GPO2_INIT 0x0
#define XPAR_IOMODULE_0_USE_GPO3 0x0
#define XPAR_IOMODULE_0_GPO3_SIZE 0x20
#define XPAR_IOMODULE_0_GPO3_INIT 0x0
#define XPAR_IOMODULE_0_USE_GPO4 0x0
#define XPAR_IOMODULE_0_GPO4_SIZE 0x20
#define XPAR_IOMODULE_0_GPO4_INIT 0x0
#define XPAR_IOMODULE_0_USE_GPI1 0x1
#define XPAR_IOMODULE_0_GPI1_SIZE 0x8
#define XPAR_IOMODULE_0_GPI1_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_GPI2 0x0
#define XPAR_IOMODULE_0_GPI2_SIZE 0x20
#define XPAR_IOMODULE_0_GPI2_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_GPI3 0x0
#define XPAR_IOMODULE_0_GPI3_SIZE 0x20
#define XPAR_IOMODULE_0_GPI3_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_GPI4 0x0
#define XPAR_IOMODULE_0_GPI4_SIZE 0x20
#define XPAR_IOMODULE_0_GPI4_INTERRUPT 0x0
#define XPAR_IOMODULE_0_USE_IO_BUS 0x0
#define XPAR_IOMODULE_0_IO_MASK 0xc0000000
#define XPAR_IOMODULE_0_FREQ 0x2faf080
#define XPAR_IOMODULE_0_IO_BASEADDR 0xc0000000

/* Canonical definitions for peripheral IOMODULE_0 */
#define XPAR_XIOMODULE_0_BASEADDR 0x80000000
#define XPAR_XIOMODULE_0_HIGHADDR 0x8000ffff
#define XPAR_XIOMODULE_0_COMPATIBLE "xlnx,iomodule-3.1"
#define XPAR_XIOMODULE_0_CLOCK_FREQ 0x2faf080
#define XPAR_XIOMODULE_0_FIT1_NO_CLOCKS 0x1848
#define XPAR_XIOMODULE_0_FIT1_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_FIT2_NO_CLOCKS 0x1848
#define XPAR_XIOMODULE_0_FIT2_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_FIT3_NO_CLOCKS 0x1848
#define XPAR_XIOMODULE_0_FIT3_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_FIT4_NO_CLOCKS 0x1848
#define XPAR_XIOMODULE_0_FIT4_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_FREQ 0x2faf080
#define XPAR_XIOMODULE_0_GPO_INIT_0 0
#define XPAR_XIOMODULE_0_GPO_INIT_1 0
#define XPAR_XIOMODULE_0_GPO_INIT_2 0
#define XPAR_XIOMODULE_0_GPO_INIT_3 0
#define XPAR_XIOMODULE_0_GPO1_SIZE 0x8
#define XPAR_XIOMODULE_0_GPO1_INIT 0x0
#define XPAR_XIOMODULE_0_GPO2_SIZE 0x10
#define XPAR_XIOMODULE_0_GPO2_INIT 0x0
#define XPAR_XIOMODULE_0_GPO3_SIZE 0x20
#define XPAR_XIOMODULE_0_GPO3_INIT 0x0
#define XPAR_XIOMODULE_0_GPO4_SIZE 0x20
#define XPAR_XIOMODULE_0_GPO4_INIT 0x0
#define XPAR_XIOMODULE_0_GPI1_SIZE 0x8
#define XPAR_XIOMODULE_0_GPI1_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_GPI2_SIZE 0x20
#define XPAR_XIOMODULE_0_GPI2_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_GPI3_SIZE 0x20
#define XPAR_XIOMODULE_0_GPI3_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_GPI4_SIZE 0x20
#define XPAR_XIOMODULE_0_GPI4_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_INTC_HAS_FAST 0x1
#define XPAR_XIOMODULE_0_INTC_BASE_VECTORS 0x0
#define XPAR_XIOMODULE_0_INTC_ADDR_WIDTH 0x10
#define XPAR_XIOMODULE_0_INTC_LEVEL_EDGE 0x7fff
#define XPAR_XIOMODULE_0_INTC_INTR_SIZE 0x1
#define XPAR_XIOMODULE_0_INTC_USE_EXT_INTR 0x0
#define XPAR_XIOMODULE_0_INTC_POSITIVE 0xffff
#define XPAR_XIOMODULE_0_IO_MASK 0xc0000000
#define XPAR_XIOMODULE_0_IO_BASEADDR 0xc0000000
#define XPAR_XIOMODULE_0_MAX_INTR_SIZE 0x0
#define XPAR_XIOMODULE_0_OPTIONS 0x1
#define XPAR_XIOMODULE_0_PIT_USED_0 0
#define XPAR_XIOMODULE_0_PIT_USED_1 0
#define XPAR_XIOMODULE_0_PIT_USED_2 0
#define XPAR_XIOMODULE_0_PIT_USED_3 0
#define XPAR_XIOMODULE_0_PIT_SIZE_0 32
#define XPAR_XIOMODULE_0_PIT_SIZE_1 32
#define XPAR_XIOMODULE_0_PIT_SIZE_2 32
#define XPAR_XIOMODULE_0_PIT_SIZE_3 32
#define XPAR_XIOMODULE_0_PIT_MASK_0 4294967295
#define XPAR_XIOMODULE_0_PIT_MASK_1 4294967295
#define XPAR_XIOMODULE_0_PIT_MASK_2 4294967295
#define XPAR_XIOMODULE_0_PIT_MASK_3 4294967295
#define XPAR_XIOMODULE_0_PIT_PRESCALER_0 0
#define XPAR_XIOMODULE_0_PIT_PRESCALER_1 0
#define XPAR_XIOMODULE_0_PIT_PRESCALER_2 0
#define XPAR_XIOMODULE_0_PIT_PRESCALER_3 0
#define XPAR_XIOMODULE_0_PIT_READABLE_0 1
#define XPAR_XIOMODULE_0_PIT_READABLE_1 1
#define XPAR_XIOMODULE_0_PIT_READABLE_2 1
#define XPAR_XIOMODULE_0_PIT_READABLE_3 1
#define XPAR_XIOMODULE_0_PIT1_SIZE 0x20
#define XPAR_XIOMODULE_0_PIT1_READABLE 0x1
#define XPAR_XIOMODULE_0_PIT1_PRESCALER 0x0
#define XPAR_XIOMODULE_0_PIT1_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_PIT2_SIZE 0x20
#define XPAR_XIOMODULE_0_PIT2_READABLE 0x1
#define XPAR_XIOMODULE_0_PIT2_PRESCALER 0x0
#define XPAR_XIOMODULE_0_PIT2_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_PIT3_SIZE 0x20
#define XPAR_XIOMODULE_0_PIT3_READABLE 0x1
#define XPAR_XIOMODULE_0_PIT3_PRESCALER 0x0
#define XPAR_XIOMODULE_0_PIT3_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_PIT4_SIZE 0x20
#define XPAR_XIOMODULE_0_PIT4_READABLE 0x1
#define XPAR_XIOMODULE_0_PIT4_PRESCALER 0x0
#define XPAR_XIOMODULE_0_PIT4_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_UART_BAUDRATE 0x1c200
#define XPAR_XIOMODULE_0_UART_PROG_BAUDRATE 0x0
#define XPAR_XIOMODULE_0_UART_DATA_BITS 0x8
#define XPAR_XIOMODULE_0_UART_USE_PARITY 0x0
#define XPAR_XIOMODULE_0_UART_ODD_PARITY 0x0
#define XPAR_XIOMODULE_0_UART_RX_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_UART_TX_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_USE_UART_RX 0x1
#define XPAR_XIOMODULE_0_USE_UART_TX 0x1
#define XPAR_XIOMODULE_0_UART_ERROR_INTERRUPT 0x0
#define XPAR_XIOMODULE_0_USE_FIT1 0x0
#define XPAR_XIOMODULE_0_USE_FIT2 0x0
#define XPAR_XIOMODULE_0_USE_FIT3 0x0
#define XPAR_XIOMODULE_0_USE_FIT4 0x0
#define XPAR_XIOMODULE_0_USE_PIT1 0x0
#define XPAR_XIOMODULE_0_USE_PIT2 0x0
#define XPAR_XIOMODULE_0_USE_PIT3 0x0
#define XPAR_XIOMODULE_0_USE_PIT4 0x0
#define XPAR_XIOMODULE_0_USE_GPO1 0x1
#define XPAR_XIOMODULE_0_USE_GPO2 0x1
#define XPAR_XIOMODULE_0_USE_GPO3 0x0
#define XPAR_XIOMODULE_0_USE_GPO4 0x0
#define XPAR_XIOMODULE_0_USE_GPI1 0x1
#define XPAR_XIOMODULE_0_USE_GPI2 0x0
#define XPAR_XIOMODULE_0_USE_GPI3 0x0
#define XPAR_XIOMODULE_0_USE_GPI4 0x0
#define XPAR_XIOMODULE_0_USE_IO_BUS 0x0

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral MDM_0 */
#define XPAR_MDM_0_COMPATIBLE "xlnx,mdm-riscv-1.0"
#define XPAR_MDM_0_BASEADDR 0x40000000
#define XPAR_MDM_0_HIGHADDR 0x4000ffff

/* Canonical definitions for peripheral MDM_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40000000
#define XPAR_XUARTLITE_0_HIGHADDR 0x4000ffff
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,mdm-riscv-1.0"

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0xffff

/*  CPU parameters definition */
#define XPAR_MICROBLAZE_RISCV_TIMEBASE_FREQUENCY 50000000
#define XPAR_MICROBLAZE_RISCV_FREQ 50000000
#define XPAR_MICROBLAZE_RISCV_BASE_VECTORS 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_MULDIV 0
#define XPAR_MICROBLAZE_RISCV_USE_ATOMIC 0
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_D_CACHE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_D_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_RISCV_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_D_CACHE_BASEADDR 0
#define XPAR_MICROBLAZE_RISCV_D_CACHE_HIGHADDR 1073741823
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_REG 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 50000000

#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0

#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0

#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_FPU 0

#define XPAR_MICROBLAZE_RISCV_USE_MMU 0

#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0

#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0

#define XPAR_MICROBLAZE_RISCV_D_LMB 1

#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0

#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

#define XPAR_MICROBLAZE_RISCV_ADDR_SIZE 32

/* Device ID */
#define XPAR_DEVICE_ID "7z010"

#endif  /* end of protection macro */